name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
        - name: Obter o código do projeto
          uses: actions/checkout@v4

        - name: Autenticar no Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push da Imagem Docker
          uses: docker/build-push-action@v6
          with:
            context: ./src
            file: ./src/Dockerfile
            push: true
            tags: |
              wandersonvinhal/fake-shop:latest
              wandersonvinhal/fake-shop:v${{ github.run_number }}

    CD:
      runs-on: ubuntu-latest
      steps:
        - name: Action de teste
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1