name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
        - name: Action de teste
          uses: actions/checkout@v4

        - name: Autenticar no Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}